"""Extract text
Exract wav-sentence text file fom the wer file generated by wenet's tools
"""
import argparse
import json
import os
def extract_text(jsonl_path):
    text = dict()
    with open(jsonl_path) as f:
        for line in f:
            data = json.loads(line)
            if data["source"] in text:
                text[data["source"]].append([os.path.basename(data["audio"]).split(".")[0],data["gt"]])
            else:
                text[data["source"]] = [[os.path.basename(data["audio"]).split(".")[0],data["gt"]]]
    for item in text:
        # print(os.path.join(os.path.dirname(jsonl_path),item))
        with open(os.path.join(os.path.dirname(jsonl_path),item),"w") as f:
            for line in text[item]:
                f.write(line[0]+" "+line[1]+"\n")

# def main():
#     parse = argparse.ArgumentParser()
#     parse.add_argument("--wer_path")
#     parse.add_argument("--outpub_path")
#     pass

if __name__ == "__main__":
    parse = argparse.ArgumentParser()
    parse.add_argument("path")
    args = parse.parse_args()
    for path,dirs,files in os.walk(args.path):
        for file in files:
            if "jsonl" in file:
                print(os.path.join(path,file))
                extract_text(os.path.join(path,file))
