"""Extract text
Exract wav-sentence text file fom the wer file generated by wenet's tools
"""
import argparse
import os
def extract_text(wer_path,output_path,language="English"):
    utts = []
    labs = []
    with open(wer_path) as f:
        count = 0
        for line in f:
            count+=1
            if count % 6 == 2 and line[0:3] == "utt":
                utts.append(line[4:].strip())
            if count % 6 == 4 and line[0:3] == "lab":
                if language in ["Chinese"]:
                    labs.append(line[4:].strip().replace(" ",""))
                else:
                    labs.append(line[4:].strip())
    assert(len(utts) == len(labs))
    with open(output_path,"a+") as f:
        for utt,lab in zip(utts,labs):
            f.write(utt+" "+lab+"\n")

# def main():
#     parse = argparse.ArgumentParser()
#     parse.add_argument("--wer_path")
#     parse.add_argument("--outpub_path")
#     pass

if __name__ == "__main__":
    parse = argparse.ArgumentParser()
    parse.add_argument("path")
    parse.add_argument("--language",default="English")
    args = parse.parse_args()
    print(args)
    for path,dirs,files in os.walk(args.path):
        if "wer" in files:
            print(os.path.join(path,"wer"))
            extract_text(os.path.join(path,"wer"),os.path.join(args.path,"text"),args.language)
